# Generated by Django 5.2.3 on 2025-06-29 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('auc_score', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='healthy', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('step', models.IntegerField(help_text='Time step in simulation')),
                ('type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('CASH_OUT', 'Cash Out'), ('PAYMENT', 'Payment'), ('CASH_IN', 'Cash In'), ('DEBIT', 'Debit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('name_orig', models.CharField(help_text='Origin account name', max_length=50)),
                ('old_balance_orig', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_balance_orig', models.DecimalField(decimal_places=2, max_digits=15)),
                ('name_dest', models.CharField(help_text='Destination account name', max_length=50)),
                ('old_balance_dest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_balance_dest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('fraud_prediction', models.CharField(blank=True, choices=[('LEGITIMATE', 'Legitimate'), ('FRAUD', 'Fraud')], max_length=20, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('MINIMAL', 'Minimal'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(default='Douala, Cameroon', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
